language: ruby

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false -J-Xmx1g"

cache: bundler

rvm:
  - "jruby-1.7.19"
  - "2.2.2"

services:
  - redis-server

before_script:
  - 'cp config/travis.example.yml config/travis.yml'

